'\" t

.TH "COMBINATORICA CLASSICA" "8" "26\ \&FEBRARY\ \&2024" "COMBINATORICA CLASSICA 9.9.9" "COMBINATORICA CLASSICA"

.SH "NAME"
Combinatorica classica
.SH "SYNOPSIS"
Combinatorica classica 

   /usr/local/bin/arrangements_no_repetitions.comb  2 1
   /usr/local/bin/compositions.comb  2
   /usr/local/bin/arrangements_with_repetitions.comb  2 2
   /usr/local/bin/partitions.comb 2
   /usr/local/bin/combinations.comb 3 2
   /usr/local/bin/permutations.comb 123
   /usr/local/bin/combinations_with_repetitions.comb 3 2
   /usr/local/bin/permutations_with_repetitions.comb 112

.SH "DESCRIPTION"

\fBCombinatorica classica\fR  - пакет классических итеративных алгоритмов переборной комбинаторики,
который включает в себя следующие реализации (8 классических алгоритмов):
 1) Перестановки (permutations).
 2) Перестановки с повторением (permutations with repetitions).
 3) Размещения (arrangements).
 4) Размещения с повторением (arrangements with repetitions).
 5) Сочетания (combinations).
 6) Сочетания с повторением (combinations with repetitions).
 7) Разбиения (partitions).
 8) Композиции (compositions).
Алгоритмы осуществляют порождение (генерацию) всех значений.
Ввод значения осуществляется через аргумент командной строки, вывод на терминал.

.SH "INSTALL"
chmod +x ./install.sh
	Run  ./install.sh
	All compiled programs will be in bin/

	Установка
	Запустите:
	chmod +x ./install.sh
	Run  ./install.sh

	Сompile standalone program:
	gcc permutations.c -o permutations.comb
	Run:
	./permutations.comb 123

.SH "AUTHORS"

By Ivan Gavryushin (dcc0. MSK. 2010-2020): <dcc0@mail.ru>,<dcc0@yandex.ru>,<ivangavr777@gmail.com>
