'\" t

.TH "COMBINATORICA CLASSICA" "8" "26\ \&FEBRARY\ \&2024" "COMBINATORICA CLASSICA 9.9.9" "COMBINATORICA CLASSICA"

.SH "NAME"
Combinatorica classica
.SH "SYNOPSIS"
Combinatorica classica

   /usr/local/bin/arrangements_no_repetitions.comb  2 1
   /usr/local/bin/compositions.comb  2
   /usr/local/bin/arrangements_with_repetitions.comb  2 2
   /usr/local/bin/partitions.comb 2
   /usr/local/bin/combinations.comb 3 2
   /usr/local/bin/permutations.comb 123
   /usr/local/bin/combinations_with_repetitions.comb 3 2
   /usr/local/bin/permutations_with_repetitions.comb 112

.SH "DESCRIPTION"

\fBCombinatorica classica\fR  -  a set of  8 classical iterative, generative combinatorial algorithms:
 1) Permutations
 2) Permutations with repetitions
 3) Arrangements
 4) Arrangements with repetitions
 5) Combinations
 6) combinations with repetitions.
 7) Partitions
 8) Compositions

.SH "INSTALL"

chmod +x ./install.sh
Run  ./install.sh
All compiled programs will be in bin/
Сompile standalone program:
gcc permutations.c -o permutations.comb
Run:
./permutations.comb 123

.SH "AUTHORS"

By Ivan Gavryushin (dcc0. MSK. 2010-2020): mol0t@list.ru,dcc0@yandex.ru,ivangavr777@gmail.com
